CREATE OR REPLACE FILE FORMAT csv_format
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    SKIP_BLANK_LINES = TRUE
    COMPRESSION = AUTO
    EMPTY_FIELD_AS_NULL = TRUE;